### PR TITLE
- initial appveyor.yml CI config

### PR DESCRIPTION
**Pull request by chcg**
- added missing dependency of CSScriptNpp to DbgAgent

, see https://ci.appveyor.com/project/chcg/cs-script-npp/build/1.7.6.18

- vs2017 (https://ci.appveyor.com/project/chcg/cs-script-npp/build/1.7.6.18/job/28pchyo4y3a3jm5w) misses:

> C:\projects\cs-script-npp\src\CSScriptNpp.2017.sln.metaproj : error MSB3202: The project file "C:\projects\cs-script-npp\src\launcher\launcher.csproj" was not found. [C:\projects\cs-script-npp\src\CSScriptNpp.2017.sln]

- vs2015 (https://ci.appveyor.com/project/chcg/cs-script-npp/build/1.7.6.18/job/94y91wc7rf62j5c2) issues with missing assemblies:

> "C:\projects\cs-script-npp\src\Formatter\Formatter.csproj" (default target) (21) ->
> (CoreCompile target) -> 
>   Program.cs(6,44): error CS0234: The type or namespace name 'Formatting' does not exist in the namespace 'Microsoft.CodeAnalysis' (are you missing an assembly reference?) [C:\projects\cs-script-npp\src\Formatter\Formatter.csproj]
>   Program.cs(8,30): error CS0234: The type or namespace name 'Formatting' does not exist in the namespace 'Microsoft.CodeAnalysis' (are you missing an assembly reference?) [C:\projects\cs-script-npp\src\Formatter\Formatter.csproj]
>   Program.cs(9,30): error CS0234: The type or namespace name 'MSBuild' does not exist in the namespace 'Microsoft.CodeAnalysis' (are you missing an assembly reference?) [C:\projects\cs-script-npp\src\Formatter\Formatter.csproj]
>   Program.cs(12,37): error CS0234: The type or namespace name 'Formatting' does not exist in the namespace 'Microsoft.CodeAnalysis.CSharp' (are you missing an assembly reference?) [C:\projects\cs-script-npp\src\Formatter\Formatter.csproj]
>   Program.cs(36,16): error CS0246: The type or namespace name 'MSBuildWorkspace' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\cs-script-npp\src\Formatter\Formatter.csproj]
>   Program.cs(35,16): error CS0246: The type or namespace name 'MSBuildWorkspace' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\cs-script-npp\src\Formatter\Formatter.csproj]

### CODE REVIEW

**Comment by chcg** [comment]
@oleg-shilo Yes mainly the possibility to integrate this github project with appveyor to automatically have an intependant build status+ a correction for the missing build dependency of CSScriptNpp to DbgAgent which showed up during the CI build.

**Comment by oleg-shilo** [comment]
All done. Thank you.

**Comment by chcg** [comment]
@oleg-shilo Hi, with https://github.com/oleg-shilo/cs-script.npp/commit/ec9b8f4ef1c7adfd41b4a0c99f90601521176590#diff-c3e4ae90897c8b0b4a65dd1fd2fce812 you added a project launcher to build launcher.exe to the VS2017 solution. This project is not part of this github repo. Is this intended?

**Comment by oleg-shilo** [comment]
No, it's just a mistake. 
Corrected now.

**Pull request merged**
